import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-ar-short-pay-deduction-recovery",
  "engine": "recovery",
  "title": "Accounts Receivable Short-Pay & Deduction Recovery",
  "shortTitle": "AR Deduction Recovery",
  "tagline": "Explain every short payment and turn unsupported customer deductions into collected cash",
  "industry": "B2B Receivables Recovery",
  "uiPort": 4574,
  "apiPort": 5574,
  "accent": "#b45309",
  "currency": "USD",
  "primaryOutcome": "Short-pays and invalid deductions resolved with complete evidence, deadlines, ownership, and cash reconciliation",
  "valueNarrative": "Link contracts, invoices, remittances, deductions, delivery evidence, correspondence, credit memos, and cash to accelerate recovery.",
  "calculation": {
    "actualKey": "paidAmount",
    "expectedKey": "netDueAmount",
    "actualLabel": "Customer Paid Amount",
    "expectedLabel": "Supported Net Amount Due",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Invoice, contract, remittance, and fulfillment evidence indicate an unsupported customer short payment.",
    "actions": [
      "Validate the governing agreement and effective rules",
      "Reconcile transaction-level source evidence",
      "Prepare and submit the recovery or correction package",
      "Track response and reconcile realized financial outcome"
    ]
  }
},[
feature("customer-contract-and-price-library","ADR01","Customer contract and price library","Reconcile customer contract and price library using customer contracts, price lists, invoices, remittances, deduction codes, proof of delivery, promotions, tax support, correspondence, and credit memos.","Produce a governed customer contract and price library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["customerInvoice","Customer / Invoice","text","Harbor Retail / INV-884120"],["caseReference","Customer contract and price library Reference","text","ADR01-2026-001"],["paidAmount","Customer Paid Amount","currency",742000],["netDueAmount","Supported Net Amount Due","currency",886500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Distributor short-pay","Retail customer deduction","Freight deduction","Damage claim deduction","Unauthorized discount"]}),
feature("invoice-and-receivable-ingestion","ADR02","Invoice and receivable ingestion","Reconcile invoice and receivable ingestion using customer contracts, price lists, invoices, remittances, deduction codes, proof of delivery, promotions, tax support, correspondence, and credit memos.","Produce a governed invoice and receivable ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["customerInvoice","Customer / Invoice","text","Harbor Retail / INV-884120"],["caseReference","Invoice and receivable ingestion Reference","text","ADR02-2026-001"],["paidAmount","Customer Paid Amount","currency",742000],["netDueAmount","Supported Net Amount Due","currency",886500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Distributor short-pay","Retail customer deduction","Freight deduction","Damage claim deduction","Unauthorized discount"]}),
feature("cash-and-lockbox-matching","ADR03","Cash and lockbox matching","Reconcile cash and lockbox matching using customer contracts, price lists, invoices, remittances, deduction codes, proof of delivery, promotions, tax support, correspondence, and credit memos.","Produce a governed cash and lockbox matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["customerInvoice","Customer / Invoice","text","Harbor Retail / INV-884120"],["caseReference","Cash and lockbox matching Reference","text","ADR03-2026-001"],["paidAmount","Customer Paid Amount","currency",742000],["netDueAmount","Supported Net Amount Due","currency",886500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Distributor short-pay","Retail customer deduction","Freight deduction","Damage claim deduction","Unauthorized discount"]}),
feature("short-payment-detection","ADR04","Short-payment detection","Reconcile short-payment detection using customer contracts, price lists, invoices, remittances, deduction codes, proof of delivery, promotions, tax support, correspondence, and credit memos.","Produce a governed short-payment detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["customerInvoice","Customer / Invoice","text","Harbor Retail / INV-884120"],["caseReference","Short-payment detection Reference","text","ADR04-2026-001"],["paidAmount","Customer Paid Amount","currency",742000],["netDueAmount","Supported Net Amount Due","currency",886500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Distributor short-pay","Retail customer deduction","Freight deduction","Damage claim deduction","Unauthorized discount"]}),
feature("deduction-reason-classification","ADR05","Deduction reason classification","Reconcile deduction reason classification using customer contracts, price lists, invoices, remittances, deduction codes, proof of delivery, promotions, tax support, correspondence, and credit memos.","Produce a governed deduction reason classification decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["customerInvoice","Customer / Invoice","text","Harbor Retail / INV-884120"],["caseReference","Deduction reason classification Reference","text","ADR05-2026-001"],["paidAmount","Customer Paid Amount","currency",742000],["netDueAmount","Supported Net Amount Due","currency",886500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Distributor short-pay","Retail customer deduction","Freight deduction","Damage claim deduction","Unauthorized discount"]}),
feature("unauthorized-discount-detection","ADR06","Unauthorized discount detection","Reconcile unauthorized discount detection using customer contracts, price lists, invoices, remittances, deduction codes, proof of delivery, promotions, tax support, correspondence, and credit memos.","Produce a governed unauthorized discount detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["customerInvoice","Customer / Invoice","text","Harbor Retail / INV-884120"],["caseReference","Unauthorized discount detection Reference","text","ADR06-2026-001"],["paidAmount","Customer Paid Amount","currency",742000],["netDueAmount","Supported Net Amount Due","currency",886500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Distributor short-pay","Retail customer deduction","Freight deduction","Damage claim deduction","Unauthorized discount"]}),
feature("freight-deduction-validation","ADR07","Freight deduction validation","Reconcile freight deduction validation using customer contracts, price lists, invoices, remittances, deduction codes, proof of delivery, promotions, tax support, correspondence, and credit memos.","Produce a governed freight deduction validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["customerInvoice","Customer / Invoice","text","Harbor Retail / INV-884120"],["caseReference","Freight deduction validation Reference","text","ADR07-2026-001"],["paidAmount","Customer Paid Amount","currency",742000],["netDueAmount","Supported Net Amount Due","currency",886500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Distributor short-pay","Retail customer deduction","Freight deduction","Damage claim deduction","Unauthorized discount"]}),
feature("damage-deduction-validation","ADR08","Damage deduction validation","Reconcile damage deduction validation using customer contracts, price lists, invoices, remittances, deduction codes, proof of delivery, promotions, tax support, correspondence, and credit memos.","Produce a governed damage deduction validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["customerInvoice","Customer / Invoice","text","Harbor Retail / INV-884120"],["caseReference","Damage deduction validation Reference","text","ADR08-2026-001"],["paidAmount","Customer Paid Amount","currency",742000],["netDueAmount","Supported Net Amount Due","currency",886500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Distributor short-pay","Retail customer deduction","Freight deduction","Damage claim deduction","Unauthorized discount"]}),
feature("promotion-allowance-validation","ADR09","Promotion allowance validation","Reconcile promotion allowance validation using customer contracts, price lists, invoices, remittances, deduction codes, proof of delivery, promotions, tax support, correspondence, and credit memos.","Produce a governed promotion allowance validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["customerInvoice","Customer / Invoice","text","Harbor Retail / INV-884120"],["caseReference","Promotion allowance validation Reference","text","ADR09-2026-001"],["paidAmount","Customer Paid Amount","currency",742000],["netDueAmount","Supported Net Amount Due","currency",886500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Distributor short-pay","Retail customer deduction","Freight deduction","Damage claim deduction","Unauthorized discount"]}),
feature("tax-and-pricing-analysis","ADR10","Tax and pricing analysis","Reconcile tax and pricing analysis using customer contracts, price lists, invoices, remittances, deduction codes, proof of delivery, promotions, tax support, correspondence, and credit memos.","Produce a governed tax and pricing analysis decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["customerInvoice","Customer / Invoice","text","Harbor Retail / INV-884120"],["caseReference","Tax and pricing analysis Reference","text","ADR10-2026-001"],["paidAmount","Customer Paid Amount","currency",742000],["netDueAmount","Supported Net Amount Due","currency",886500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Distributor short-pay","Retail customer deduction","Freight deduction","Damage claim deduction","Unauthorized discount"]}),
feature("proof-of-delivery-matching","ADR11","Proof-of-delivery matching","Reconcile proof-of-delivery matching using customer contracts, price lists, invoices, remittances, deduction codes, proof of delivery, promotions, tax support, correspondence, and credit memos.","Produce a governed proof-of-delivery matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["customerInvoice","Customer / Invoice","text","Harbor Retail / INV-884120"],["caseReference","Proof-of-delivery matching Reference","text","ADR11-2026-001"],["paidAmount","Customer Paid Amount","currency",742000],["netDueAmount","Supported Net Amount Due","currency",886500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Distributor short-pay","Retail customer deduction","Freight deduction","Damage claim deduction","Unauthorized discount"]}),
feature("evidence-request-workflow","ADR12","Evidence request workflow","Reconcile evidence request workflow using customer contracts, price lists, invoices, remittances, deduction codes, proof of delivery, promotions, tax support, correspondence, and credit memos.","Produce a governed evidence request workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["customerInvoice","Customer / Invoice","text","Harbor Retail / INV-884120"],["caseReference","Evidence request workflow Reference","text","ADR12-2026-001"],["paidAmount","Customer Paid Amount","currency",742000],["netDueAmount","Supported Net Amount Due","currency",886500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Distributor short-pay","Retail customer deduction","Freight deduction","Damage claim deduction","Unauthorized discount"]}),
feature("customer-dispute-package","ADR13","Customer dispute package","Reconcile customer dispute package using customer contracts, price lists, invoices, remittances, deduction codes, proof of delivery, promotions, tax support, correspondence, and credit memos.","Produce a governed customer dispute package decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["customerInvoice","Customer / Invoice","text","Harbor Retail / INV-884120"],["caseReference","Customer dispute package Reference","text","ADR13-2026-001"],["paidAmount","Customer Paid Amount","currency",742000],["netDueAmount","Supported Net Amount Due","currency",886500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Distributor short-pay","Retail customer deduction","Freight deduction","Damage claim deduction","Unauthorized discount"]}),
feature("deadline-and-aging-control","ADR14","Deadline and aging control","Reconcile deadline and aging control using customer contracts, price lists, invoices, remittances, deduction codes, proof of delivery, promotions, tax support, correspondence, and credit memos.","Produce a governed deadline and aging control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["customerInvoice","Customer / Invoice","text","Harbor Retail / INV-884120"],["caseReference","Deadline and aging control Reference","text","ADR14-2026-001"],["paidAmount","Customer Paid Amount","currency",742000],["netDueAmount","Supported Net Amount Due","currency",886500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Distributor short-pay","Retail customer deduction","Freight deduction","Damage claim deduction","Unauthorized discount"]}),
feature("recovered-cash-reconciliation","ADR15","Recovered cash reconciliation","Reconcile recovered cash reconciliation using customer contracts, price lists, invoices, remittances, deduction codes, proof of delivery, promotions, tax support, correspondence, and credit memos.","Produce a governed recovered cash reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["customerInvoice","Customer / Invoice","text","Harbor Retail / INV-884120"],["caseReference","Recovered cash reconciliation Reference","text","ADR15-2026-001"],["paidAmount","Customer Paid Amount","currency",742000],["netDueAmount","Supported Net Amount Due","currency",886500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Distributor short-pay","Retail customer deduction","Freight deduction","Damage claim deduction","Unauthorized discount"]}),
feature("customer-root-cause-analytics","ADR16","Customer root-cause analytics","Reconcile customer root-cause analytics using customer contracts, price lists, invoices, remittances, deduction codes, proof of delivery, promotions, tax support, correspondence, and credit memos.","Produce a governed customer root-cause analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["customerInvoice","Customer / Invoice","text","Harbor Retail / INV-884120"],["caseReference","Customer root-cause analytics Reference","text","ADR16-2026-001"],["paidAmount","Customer Paid Amount","currency",742000],["netDueAmount","Supported Net Amount Due","currency",886500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Distributor short-pay","Retail customer deduction","Freight deduction","Damage claim deduction","Unauthorized discount"]})
]);
